Fix conversion for empty interface slices
Because an awkward backward compatibility construct in mapstructure when
using WeakDecode, the test added in this commit fails without the change
to use Decode over WeakDecode, in the following manner:

```
$ go test ./...
--- FAIL: TestInterfaceToVariable (0.00s)
	convert_test.go:181: empty list:
		Expected: {Variable (TypeList): []}
		     Got: {Variable (TypeMap): map[]}
FAIL
FAIL	github.com/hashicorp/hil	0.008s
ok  	github.com/hashicorp/hil/ast	0.007s
```